# Change these first
owner: scidroid # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website / Blog / Portfolio
    url: https://scidroid.co
  - name: API endpoint
    url: https://scidroid.co/api/view/test
  - name: Image hosting
    url: https://s2.loli.net
  - name: Email sender API
    url: $EMAIL_ENDPOINT
  - name: Automations API
    url: $SPLITBEE_ENDPOINT

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.scidroid.co
  # baseUrl: /your-repo-name
  logoUrl: https://scidroid.co/avatar.png
  favicon: https://scidroid.co/avatar.png
  name: SciDroid's status page
  introTitle: "Get the status of my websites in **real time**"
  navbar:
    - title: Status
      href: /
    - title: Portfolio
      href: https://scidroid.co

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
